### ISSUE TITLE
Variable $'error-codes' is undefined

### ISSUE THREAD

**Issue by glen-84** [pdt-eg/Core-Plugin#159]
```php
if (in_array('invalid-input-response', $data->{'error-codes'})) {
    return false;
}
```

... false positive?

**Comment by zulus** [comment]
Yes, I completely forgot about this kind of variables.

I'm currently during moving this validator to PDT 6.0, so probably fix on that side.

**Comment by glen-84** [comment]
Awesome, sounds good.

Will you also be considering #103, #157 and #158 while working on this?

**Comment by zulus** [comment]
This definitely.  Path for PDT already fixes: https://bugs.eclipse.org/bugs/show_bug.cgi?id=398019

* #157  - Work fine in upcoming patch also
* #158 -  Sounds like design issue, I prefer make it configurable
* #103 - In current DLTK/PDT state this will introduce huge performance regression, so I'll probably limit this into global functions only

**Comment by glen-84** [comment]
* #157 - Great!
* #158 - Sounds fair.
* #103 - Are you referring to the "autocreated" variables part of this issue? (or the static part)

**Comment by zulus** [comment]
Fixed on PDT (already released).

**Comment by glen-84** [comment]
@zulus This is still not working in `PHP Development Tools (PDT) 6.0.0.201806122250`.

**Comment by zulus** [comment]
This works fine as I see:

```PHP
if (in_array('invalid-input-response', $data->{'error-codes'})) {
    return false;
}
```

**Comment by zulus** [comment]
You have outdated PEX plugin, I forgot push p2 website, sorry, could you update?

**Comment by zulus** [comment]
Recent stable version is 0.24, current dev is 0.25.

**Comment by glen-84** [comment]
No updates were found.

**Comment by zulus** [comment]
Restart eclipse first please. This is composite update site ans eclipse cache it.

**Comment by glen-84** [comment]
I tried that twice. I'll try again tomorrow.

Thanks.

**Comment by glen-84** [comment]
It worked now, and the errors are gone. Thanks for your help.
